export const COLORS = {
  sunday: {
    name: 'Sunday Morning',
    background: '#EDE4D2',
    backgroundDark: '#6A5840',
    border: '#1A1410',
    accent: '#C4785A',
    accentLight: '#E8A98A',
    accentGold: '#D4A853',
    orbUrgent: '#C4785A',
    orbUrgentLight: '#E8A98A',
    orbMid: '#9B7FA0',
    orbMidLight: '#C4A8CA',
    orbTended: '#7A9E8C',
    orbTendedLight: '#A8C9B5',
    text: '#1A1410',
    textLight: '#5D4E47',
    tintColor: '#C4785A',
  },
  midnight: {
    name: 'Midnight Garden',
    background: '#0F1419',
    backgroundDark: '#1a2a3a',
    border: '#2a3a4a',
    accent: '#6B9BD1',
    accentLight: '#8BACD9',
    accentGold: '#D4A853',
    orbUrgent: '#E85D75',
    orbUrgentLight: '#F08896',
    orbMid: '#9B7FA0',
    orbMidLight: '#C4A8CA',
    orbTended: '#5A9E8C',
    orbTendedLight: '#78C9B5',
    text: '#FFFFFF',
    textLight: '#CCCCCC',
    tintColor: '#6B9BD1',
  },
  sugar: {
    name: 'Sugar',
    background: '#FEF5F1',
    backgroundDark: '#F5D9D0',
    border: '#E8C4B8',
    accent: '#F4A5A5',
    accentLight: '#F8C5C5',
    accentGold: '#FFD89B',
    orbUrgent: '#F4A5A5',
    orbUrgentLight: '#F8C5C5',
    orbMid: '#D9B4E0',
    orbMidLight: '#E8D0ED',
    orbTended: '#B4D9C9',
    orbTendedLight: '#D0E8DE',
    text: '#2C1810',
    textLight: '#6D4C3D',
    tintColor: '#F4A5A5',
  },
  ember: {
    name: 'Ember',
    background: '#4A1F1A',
    backgroundDark: '#2A0F0A',
    border: '#1A0A05',
    accent: '#E85D5D',
    accentLight: '#F08888',
    accentGold: '#FFB84D',
    orbUrgent: '#E85D5D',
    orbUrgentLight: '#F08888',
    orbMid: '#C4785A',
    orbMidLight: '#E8A98A',
    orbTended: '#A88860',
    orbTendedLight: '#D4A87A',
    text: '#FFFFFF',
    textLight: '#E8D9D0',
    tintColor: '#E85D5D',
  },
  cloud: {
    name: 'Cloud',
    background: '#FAFAFA',
    backgroundDark: '#F0F0F0',
    border: '#E0E0E0',
    accent: '#888888',
    accentLight: '#AAAAAA',
    accentGold: '#D4A853',
    orbUrgent: '#999999',
    orbUrgentLight: '#BBBBBB',
    orbMid: '#AAAAAA',
    orbMidLight: '#CCCCCC',
    orbTended: '#BBBBBB',
    orbTendedLight: '#DDDDDD',
    text: '#333333',
    textLight: '#666666',
    tintColor: '#888888',
  },
  noir: {
    name: 'Noir',
    background: '#000000',
    backgroundDark: '#1a1a1a',
    border: '#333333',
    accent: '#FFFFFF',
    accentLight: '#CCCCCC',
    accentGold: '#FFD700',
    orbUrgent: '#FFFFFF',
    orbUrgentLight: '#E8E8E8',
    orbMid: '#CCCCCC',
    orbMidLight: '#DDDDDD',
    orbTended: '#888888',
    orbTendedLight: '#AAAAAA',
    text: '#FFFFFF',
    textLight: '#CCCCCC',
    tintColor: '#FFFFFF',
  },
};

export const FONTS = {
  dmSans: 'dm-sans',
  cormorant: 'cormorant-garamond-italic',
  cormorantRegular: 'cormorant-garamond',
};
